config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/privacy'
  get 'home/finish'

  resources :assessments do
    collection do
      get :areas, action: :areas
    end
    member do
      get :step_1
      get :step_2
    end
    resources :teams, only: [:new, :create]
  end

  resources :teams do
    resources :assessments, only: :index
  end

  resources :users do
    member do
      get :start_assessment, action: :start_assessment
    end
  end

  root 'home#index'
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  INITAL_STATE = :start
  
  ASSESSMENT_STATES = [
    :start,
    :strong_skills_added,
    :weak_skills_added,
    :strong_attitudes_added,
    :weak_attitudes_added,
    :complete
  ]
  
  include AASM
  
  before_update :transition_state
  has_many :assessment_answers
  belongs_to :user, optional: true
  
  STRONG_SKILLS_COUNT = 5
  WEAK_SKILLS_COUNT = 2
  STRONG_ATTITUDES_COUNT = 3
  WEAK_ATTITUDES_COUNT = 1
  
  validate :check_answers, on: :update
  
  accepts_nested_attributes_for :user
  
  def strong_skills=(skills)
    set_answers('strong', 'skill', skills)
  end
  
  def weak_skills=(skills)
    set_answers('weak', 'skill', skills)
  end
  
  def strong_attitudes=(attitudes)
    set_answers('strong', 'attitude', attitudes)
  end
  
  def weak_attitudes=(attitudes)
    set_answers('weak', 'attitude', attitudes)
  end

  aasm do
    ASSESSMENT_STATES.each do |s|
      if s == INITAL_STATE
        state s, initial: true
      else
        state s
      end
    end
  end
  
  # This defines getters and setters for strong and weak skills and attitudes,
  # the setter sets assesssment_answers with the correct skill or attitude
  # and type (strong or weak), and the getter searches for the assessment answers
  # with the a skill or attitude and the given type.
  def method_missing(m, *args, &block)
    match_data = m.match /(strong|weak)_(skills|attitudes)/
    if match_data && match_data.length >= 3
      get_answers(match_data[1], match_data[2])
    else
      super
    end
  end
  
  def set_answers(answer_type, answer_class, answers)
    assessment_answers.where(id: get_assessment_answers(answer_type, answer_class.pluralize)).delete_all
    self.reload if id
    answers.each do |a|
      assessment_answers << AssessmentAnswer.new(
        "#{answer_class}_id" => (a.try(:id) || a),
        answer_type: answer_type
      )
    end
  end
  
  def get_answers(answer_type, answer_class)
    get_assessment_answers(answer_type, answer_class).map { |a| a.send(answer_class.singularize) }
  end
  
  def get_assessment_answers(answer_type, answer_class)
    answers = answer_class == 'skills' ? skill_answers : attitude_answers
    answers = answers.select { |a| a.answer_type == answer_type }
  end
  
  def skill_answers
    assessment_answers.select { |a| !a.skill.nil? }
  end
  
  def attitude_answers
    assessment_answers.select { |a| !a.attitude.nil? }
  end
  
  def get_user
    user.nil? ? User.new : user
  end
  
  def go_back
    transition_state(true)
  end
  
  def skills_by_area(type = :strong_skills)
    skills = send(type)
    skills.inject(Hash.new(0)) { |h, e| h[e.area.name] += 1 ; h }
  end
  
  private
  
    def check_answers
      if aasm_state == 'start'
        correct_number_of_strong_skills
      elsif aasm_state == 'strong_skills_added'
        correct_number_of_weak_skills
      elsif aasm_state == 'weak_skills_added'
        correct_number_of_strong_attitudes
      elsif aasm_state == 'strong_attitudes_added'
        correct_number_of_weak_attitudes
      end
    end
    
    def correct_number_of_strong_skills
      if strong_skills.count != STRONG_SKILLS_COUNT
        add_error :strong_skills, STRONG_SKILLS_COUNT
      end
    end
    
    def correct_number_of_weak_skills
      if weak_skills.count != WEAK_SKILLS_COUNT
        add_error :weak_skills, WEAK_SKILLS_COUNT
      end
    end
    
    def correct_number_of_strong_attitudes
      if strong_attitudes.count != STRONG_ATTITUDES_COUNT
        add_error :strong_attitudes, STRONG_ATTITUDES_COUNT
      end
    end
    
    def correct_number_of_weak_attitudes
      if weak_attitudes.count != WEAK_ATTITUDES_COUNT
        add_error :weak_attitudes, WEAK_ATTITUDES_COUNT
      end
    end
    
    def transition_state(back = false)
      index = ASSESSMENT_STATES.index(self.aasm_state.to_sym)
      if back
        aasm_state = ASSESSMENT_STATES[index - 1]
      else
        aasm_state = ASSESSMENT_STATES[index + 1]
      end
      update_column(:aasm_state, aasm_state) unless aasm_state.nil?
    end
    
    def add_error(attribute, count)
      errors.add attribute, error_message(attribute, count)
    end
    
    def error_message(attribute, count)
      I18n.t("activerecord.errors.models.assessment.attributes.#{attribute}.count", count: count)
    end

end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :get_areas
  prepend_before_action :get_assessment, except: [:index, :create]
  before_action :set_template, only: [:edit, :update]
  
  def index
    if params[:team_id]
      @team = Team.find(params[:team_id])
      @assessments = @team.assessments
      @users_without_assessments = @team.users_without_assessments
      render 'teams/assessments'
    end
  end
  
  def step_1
    @step = 1
  end
  
  def step_2
    @step = 2
  end
  
  def create
    @assessment = Assessment.create
    redirect_to step_1_assessment_url(@assessment)
  end
  
  def update
    if params[:back]
      @assessment.go_back
    else
      # Update the assessment
      unless @assessment.update_attributes(assessment_params)
        flash[:error] = @assessment.errors.full_messages.to_sentence
      end
    end
    # Redirect to edit or show
    if @assessment.complete?
      redirect_to assessment_url(@assessment)
    else
      redirect_to edit_assessment_url(@assessment)
    end
  end
  
  def edit
    render "assessments/#{@template}"
  end
  
  def show
  end
  
  private
  
    def get_areas
      @areas = Area.all
    end
    
    def get_assessment
      @assessment = Assessment.find(params[:id])
    end
    
    def set_template
      case @assessment.aasm_state
      when 'start'
        @step = 3
        @template = 'strong_skills'
        @skills = Skill.all
      when 'strong_skills_added'
        @step = 4
        @template = 'weak_skills'
        @skills = Skill.where.not(id: @assessment.strong_skills)
      when 'weak_skills_added'
        @step = 5
        @template = 'strong_attitudes'
        @attitudes = Attitude.all
      when 'strong_attitudes_added'
        @step = 6
        @template = 'weak_attitudes'
        @attitudes = Attitude.where.not(id: @assessment.strong_attitudes)
      when 'weak_attitudes_added'
        @step = 7
        @template = 'user'
      end
    end
    
    def assessment_params
      params.require(:assessment).permit(
        strong_skills: [],
        weak_skills: [],
        strong_attitudes: [],
        weak_attitudes: [],
        user_attributes: [
          :id, :name, :email, :organisation_type, :position, :location
        ]
      )
    end
  
end

app/views/assessments/_attitudes.html.haml
- @attitudes.each_with_index do |attitude, i|
  - selected = @assessment.send(type).include?(attitude) ? 'selected' : ''
  = render partial: 'card', locals: { obj: attitude, i: i, class_name: 'attitude', type: type, f: f, selected: selected }

app/views/assessments/_card.html.haml
.card_sort_single{ id: "card_#{i + 1}", class: "#{class_name} #{selected}", "data-type" => class_name }
  %label
    .card_title{ class: class_name }
      = obj.name
    .card_description
      = obj.description
    = f.check_box type, { multiple: true, checked: selected == 'selected' }, obj.id, nil

app/views/assessments/_results.html.haml
#strong_skills.inner_container
  .half
    %h4= t('assessments.show.strengths')
    = render partial: 'skills/skills', locals: { skills: assessment.strong_skills }
  .half
    %h4= t('assessments.show.graph_title')
    = pie_chart assessment.skills_by_area

%hr

#weak_skills.inner_container

  %h4= t('assessments.show.weaknesses')
  = render partial: 'skills/skills', locals: { skills: assessment.weak_skills }

%hr

#strong_attitudes.inner_container

  %h4= t('assessments.show.attitudes')
  = render partial: 'attitudes/attitudes', locals: { attitudes: assessment.strong_attitudes }

%hr

#weak_attitudes.inner_container

  %h4= t('assessments.show.attitudes_weak')
  = render partial: 'attitudes/attitudes', locals: { attitudes: assessment.weak_attitudes }

app/views/assessments/index.html.haml
=render partial: 'shared/step_counter'

%p=t('assessments.index.about')

- @areas.each do |a|
  .card{ class: a.name.parameterize.underscore }
    .card_title
      = a.name
    .card_description
      = a.description

.actions
  = link_to "back", :home_index, :class => "button full-button"
  = link_to "next", :new_assessment, :class => "button full-button"

app/views/assessments/new.html.haml
= render partial: 'shared/step_counter'

=t('assessments.new.about_html')

.accord_cont
  - @areas.each do |a|
    .card.accordion{ class: a.name.parameterize.underscore }
      .accord_btn.card_title
        = a.name
        %span.accord_arrow=fa_icon "chevron-down"
      .accord_content.card_description
        - a.skills.each do |s|
          .skill
            &ndash;
            = s.name

.actions
  = link_to "back", :assessments, :class => "button full-button"
  = button_to t('buttons.next'), assessments_path, method: :post, class: "button full-button right_float"

app/views/assessments/show.html.haml
#results_page
  .text_block
    %h1= t('assessments.show.next_steps.title')

    - if @assessment.user.team.present?
      =t('assessments.show.show_team.about_html')
      = link_to t('assessments.show.show_team.individual_guide'), "/downloads/individual_follow_up.pdf", class: 'button', target: '_blank'
      = link_to t('assessments.show.show_team.link'), team_assessments_path(@assessment.user.team), class: 'button blue'
    - else
      =t('assessments.show.next_steps.about_html')
      = link_to t('assessments.show.next_steps.individual_guide'), "/downloads/individual_follow_up.pdf", class: 'button', target: '_blank'
      = link_to t('assessments.show.next_steps.invite'), new_assessment_team_path(@assessment), class: 'button blue'

  %hr

  = render partial: 'results', locals: { assessment: @assessment }

.finish
  =link_to 'Finish', home_finish_path, class: 'button'

app/views/assessments/step3.html.haml
=render partial: "shared/step_counter", locals: {number: 3};

%p Let’s try and build up a picture of your skills so we can understand what strengths you bring to a team, and what your areas for development are.

%p
  Look through each of the cards below and
  %span.bold select the 5
  which you think your colleagues would use to describe your strongest skills.



#cards_sort_1.card_sorting

  #lc_1.card_sort_single.lc
    .card_title.leading_change Political & Bureaucratic Awareness
    .card_description Operating political dynamics and bureaucratic procedures to ensure strategic support.

  #lc_2.card_sort_single.lc
    .card_title.leading_change Demonstrating Value
    .card_description Creating a justification for change by articulating the value of new approaches and solutions, for decision making purposes.

  #lc_3.card_sort_single.lc
    .card_title.leading_change Storytelling & Advocacy
    .card_description Using narratives and media to articulate vision and information in compelling, engaging, humanised ways that people can connect with.

  #lc_4.card_sort_single.lc
    .card_title.leading_change Financial Change
    .card_description Understanding the many ways to liberate and use financial resources as motivation.

  #lc_5.card_sort_single.lc
    .card_title.leading_change Intrapreneurship
    .card_description Being insurgent, challenging and questioning the status quo and using business acumen to create space and opportunities for change.

  #al_1.card_sort_single.al
    .card_title.accelerating_learning Tech Literacy
    .card_description Recognizing and understanding the potential of technological developments which can improve your practice.

  #al_2.card_sort_single.al
    .card_title.accelerating_learning Systems Thinking
    .card_description Combining micro and macro perspectives to group complexity, understanding the system in a complete holistic way.

  #al_3.card_sort_single.al
    .card_title.accelerating_learning Future Acumen
    .card_description Creating and shaping a long-term vision and connecting it with short-term achievable tasks.

  #al_4.card_sort_single.al
    .card_title.accelerating_learning Data Literacy & Evidence
    .card_description Discovering, generating and interpreting different kinds of data to accelerate sense-making.

  #al_5.card_sort_single.al
    .card_title.accelerating_learning Prototyping & Iterating
    .card_description Testing ideas, using lessons of what works (and what doesn’t) to iterate them, in order to systematically improve your idea to create a more informed, robust solution to a problem.

  #wt_1.card_sort_single.wt
    .card_title.working_together Brokering
    .card_description Mediating contrasting interests and acting as a negotiator between stakeholders and partners, to reduce friction and manage diverse interests.

  #wt_2.card_sort_single.wt
    .card_title.working_together Citizen & Stakeholder Engagement
    .card_description Actively involve citizens, stakeholders and unusual suspects to bring the diverse voices of those directly, and indirectly, affected by an intervention into the conversation.

  #wt_3.card_sort_single.wt
    .card_title.working_together Building Bridges
    .card_description Orchestrating interaction to develop a common ground across teams or stakeholders, in order to create the shared ownership of and effort towards a goal.

  #wt_4.card_sort_single.wt
    .card_title.working_together Creative Facilitation
    .card_description Creatively supporting the externalisation and processing of different perspectives and facilitating the deliberation of multiple options and ideas.

=render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step4, back_link: :assess_step2};

app/views/assessments/step4.html.haml
=render partial: "shared/step_counter", locals: {number: 4};

%p Now select the 2 cards which you think your colleagues would use to describe your least strong or least well-practiced skills.


#cards_sort_2.card_sorting
  #lc_1.card_sort_single.lc
    .card_title.leading_change Political & Bureaucratic Awareness
    .card_description Operating political dynamics and bureaucratic procedures to ensure strategic support.

  #lc_2.card_sort_single.lc
    .card_title.leading_change Demonstrating Value
    .card_description Creating a justification for change by articulating the value of new approaches and solutions, for decision making purposes.

  #lc_3.card_sort_single.lc
    .card_title.leading_change Storytelling & Advocacy
    .card_description Using narratives and media to articulate vision and information in compelling, engaging, humanised ways that people can connect with.

  #lc_4.card_sort_single.lc
    .card_title.leading_change Financial Change
    .card_description Understanding the many ways to liberate and use financial resources as motivation.

  #lc_5.card_sort_single.lc
    .card_title.leading_change Intrapreneurship
    .card_description Being insurgent, challenging and questioning the status quo and using business acumen to create space and opportunities for change.

  #al_1.card_sort_single.al
    .card_title.accelerating_learning Tech Literacy
    .card_description Recognizing and understanding the potential of technological developments which can improve your practice.

  #al_2.card_sort_single.al
    .card_title.accelerating_learning Systems Thinking
    .card_description Combining micro and macro perspectives to group complexity, understanding the system in a complete holistic way.

  #al_3.card_sort_single.al
    .card_title.accelerating_learning Future Acumen
    .card_description Creating and shaping a long-term vision and connecting it with short-term achievable tasks.

  #al_4.card_sort_single.al
    .card_title.accelerating_learning Data Literacy & Evidence
    .card_description Discovering, generating and interpreting different kinds of data to accelerate sense-making.

  #al_5.card_sort_single.al
    .card_title.accelerating_learning Prototyping & Iterating
    .card_description Testing ideas, using lessons of what works (and what doesn’t) to iterate them, in order to systematically improve your idea to create a more informed, robust solution to a problem.

  #wt_1.card_sort_single.wt
    .card_title.working_together Brokering
    .card_description Mediating contrasting interests and acting as a negotiator between stakeholders and partners, to reduce friction and manage diverse interests.

  #wt_2.card_sort_single.wt
    .card_title.working_together Citizen & Stakeholder Engagement
    .card_description Actively involve citizens, stakeholders and unusual suspects to bring the diverse voices of those directly, and indirectly, affected by an intervention into the conversation.

  #wt_3.card_sort_single.wt
    .card_title.working_together Building Bridges
    .card_description Orchestrating interaction to develop a common ground across teams or stakeholders, in order to create the shared ownership of and effort towards a goal.

  #wt_4.card_sort_single.wt
    .card_title.working_together Creative Facilitation
    .card_description Creatively supporting the externalisation and processing of different perspectives and facilitating the deliberation of multiple options and ideas.

=render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step5, back_link: :assess_step3};

app/views/assessments/step5.html.haml
=render partial: "shared/step_counter", locals: {number: 5};

%p In addition to skills, our research has also identified 9 attitudes that support successful experimentation and problem solving. These differ from skills in that you will have formed them over a greater period of time and they are more difficult to learn and develop.

%p Select the 3 attributes that you think your colleagues would most likely use to describe you.


#cards_sort_3.card_sorting
  #at_1.card_sort_single
    .card_title.attitude Agile
    .card_description Responding to changing environments with flexibility.

  #at_2.card_sort_single
    .card_title.attitude Action-oriented
    .card_description Biased towards action and learning by doing.

  #at_3.card_sort_single
    .card_title.attitude Curious
    .card_description The desire to explore multiple possibilities.

  #at_4.card_sort_single
    .card_title.attitude Reflective
    .card_description Habit of critically reflecting on process and results.

  #at_5.card_sort_single
    .card_title.attitude Courageous
    .card_description Willingness to take risks.

  #at_6.card_sort_single
    .card_title.attitude Outcomes-focused
    .card_description Strong commitment to real  world effects.

  #at_7.card_sort_single
    .card_title.attitude Imaginative
    .card_description Exploring and envisioning new possible futures.

  #at_8.card_sort_single
    .card_title.attitude Resilient
    .card_description The perseverance to deal with resistance.

  #at_9.card_sort_single
    .card_title.attitude Empathetic
    .card_description Understanding others’ experiences and frames of reference.

=render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step6, back_link: :assess_step4};

app/views/assessments/step6.html.haml
=render partial: "shared/step_counter", locals: {number: 6};


%p Now select the 1 attribute that you think your colleagues would be least likely use to describe you.


#cards_sort_4.card_sorting
  #at_1.card_sort_single
    .card_title.attitude Agile
    .card_description Responding to changing environments with flexibility.

  #at_2.card_sort_single
    .card_title.attitude Action-oriented
    .card_description Biased towards action and learning by doing.

  #at_3.card_sort_single
    .card_title.attitude Curious
    .card_description The desire to explore multiple possibilities.

  #at_4.card_sort_single
    .card_title.attitude Reflective
    .card_description Habit of critically reflecting on process and results.

  #at_5.card_sort_single
    .card_title.attitude Courageous
    .card_description Willingness to take risks.

  #at_6.card_sort_single
    .card_title.attitude Outcomes-focused
    .card_description Strong commitment to real  world effects.

  #at_7.card_sort_single
    .card_title.attitude Imaginative
    .card_description Exploring and envisioning new possible futures.

  #at_8.card_sort_single
    .card_title.attitude Resilient
    .card_description The perseverance to deal with resistance.

  #at_9.card_sort_single
    .card_title.attitude Empathetic
    .card_description Understanding others’ experiences and frames of reference.


=render partial: 'shared/card_sort_footer', locals: {next_link: :home_index, back_link: :assess_step5};

app/views/assessments/strong_attitudes.html.haml
= render partial: 'shared/step_counter'

=t('assessments.strong_attitudes.about_html')

= form_for @assessment do |f|

  #cards_sort_3.card_sorting
    = render partial: 'attitudes', locals: { areas: @areas, f: f, type: :strong_attitudes }

  = render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step6, back_link: :assess_step4, f: f};

app/views/assessments/strong_skills.html.haml
= render partial: 'shared/step_counter'

=t('assessments.strong_skills.about_html')

%p
  Look through each of the cards below and
  %span.bold
    select the
    = Assessment::STRONG_SKILLS_COUNT
  which you think your colleagues would use to describe your strongest skills.

= form_for @assessment do |f|
  #cards_sort_1.card_sorting

    = render partial: 'skills', locals: { areas: @areas, f: f, type: :strong_skills }

  =render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step4, back_link: :assess_step2, f: f};

app/views/assessments/weak_attitudes.html.haml
= render partial: 'shared/step_counter'

=t('assessments.weak_attitudes.about_html')

= form_for @assessment do |f|

  #cards_sort_4.card_sorting
    = render partial: 'attitudes', locals: { areas: @areas, f: f, type: :weak_attitudes }

  = render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step6, back_link: :assess_step4, f: f};

app/views/assessments/weak_skills.html.haml
= render partial: 'shared/step_counter'

= t('assessments.weak_skills.about_html')

= form_for @assessment do |f|
  #cards_sort_2.card_sorting

    = render partial: 'skills', locals: { areas: @areas, f: f, type: :weak_skills }

  =render partial: 'shared/card_sort_footer', locals: {next_link: :assess_step5, back_link: :assess_step3, f: f};