config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/privacy'
  get 'home/finish'

  resources :assessments do
    collection do
      get :areas, action: :areas
    end
    member do
      get :step_1
      get :step_2
    end
    resources :teams, only: [:new, :create]
  end

  resources :teams do
    resources :assessments, only: :index
  end

  resources :users do
    member do
      get :start_assessment, action: :start_assessment
    end
  end

  root 'home#index'
end

app/views/shared/_card_sort_footer.html.haml
.card_sort_footer
  .inner
    .status
      Choose
      %span.num_left.bold 0
      more
      %span.card_type
    #status_indicator

    .actions
      = f.submit t('buttons.next'), :class => "button full-button fin_card_sort"

.actions
  - if @assessment.aasm_state == 'start'
    = link_to t('buttons.back'), new_assessment_path, :class => "button full-button"
  - else
    = f.submit t('buttons.back'), :name => 'back', :class => "button full-button"
  = f.submit t('buttons.next'), :class => "button full-button disabled next_button fin_card_sort"

:javascript
   window.onload = function() {
    if($(window).width() > 960)  {
      var topPoint = $('.card_sorting').position().top + 30;

      $('.card_sort_footer .inner').css('top', topPoint).css('width', $('.card_sort_footer').width()).followTo(($('.card_sorting').height()-210), topPoint);
    }
    $( window ).resize(function() {
      if($(window).width() > 960)  {
        var topPoint = $('.card_sorting').position().top + 30;

        $('.card_sort_footer .inner').css('top', topPoint).css('width', $('.card_sort_footer').width()).followTo(($('.card_sorting').height()-210), topPoint);
      }
    });
  };

app/views/shared/_step_counter.html.haml
.step_counter
  -@step.times do |i|
    .step.active
  -(7-@step).times do |i|
    .step