config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/privacy'
  get 'home/finish'

  resources :assessments do
    collection do
      get :areas, action: :areas
    end
    member do
      get :step_1
      get :step_2
    end
    resources :teams, only: [:new, :create]
  end

  resources :teams do
    resources :assessments, only: :index
  end

  resources :users do
    member do
      get :start_assessment, action: :start_assessment
    end
  end

  root 'home#index'
end

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
  - next unless msg.is_a?(String) && msg.present?
  #alerts
    %div{:class => "alert notification alert-#{name} animated slideInDown"}
      .container
        = content_tag :div, msg, :id => "flash_#{name}"
        #alert_close
          =fa_icon "times"

app/views/layouts/_html_head.html.haml
%meta{:charset => "utf-8"}
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

%link{:href => "/manifest.json", :rel => "manifest"}
%meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
%meta{:content => "#000000", :name => "theme-color"}

%title Innovation and Skills Tool

/ = favicon_link_tag 'favicon.ico'

%link{:href => "https://fonts.googleapis.com/css?family=Pontano+Sans", :rel => "stylesheet", :type => "text/css"}

= stylesheet_link_tag    "application"
= javascript_include_tag "application"
= csrf_meta_tags

app/views/layouts/_site_footer.html.haml
.container
  %h3 Keep connected
  %hr
  .half.soc_logo
    =link_to 'http://www.states-of-change.org/', target: '_blank' do
      =image_tag("logo_footer.svg")
  .half
    %p We’ll be developing our global faculty, R&D programme and learning programmes in different parts of the world over the coming months.
    %p.normal_link
      Email us at:
      =mail_to "hello@states-of-change.org"
  .full_width.fg_logo
    Created in collaboration with
    =link_to 'https://www.wearefuturegov.com/', target: '_blank' do
      =image_tag("fg_logo.png")

  .full_width.privacy
    =link_to 'Privacy policy', home_privacy_path

app/views/layouts/_site_header.html.haml
.container
  .site-header_logo
    =image_tag("logo-white.svg")

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    = render 'layouts/html_head'

  %body{:class => page_class}
    %header{:class => "site-header", :role => "banner"}
      = render "layouts/site_header"
    = render "layouts/alerts"

    %main{:class => "main", :id => "main", :role => "main"}
      .container
        = yield

    %footer{:class => "site-footer", :role => "contentinfo"}
      = render 'layouts/site_footer'